version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:    
      ZOOKEEPER_CLIENT_PORT: 2181    
      ZOOKEEPER_TICK_TIME: 2000    
      ZOOKEEPER_INIT_LIMIT: 10
    ports:
      - 2181:2181
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181", "|", "grep", "imok"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_MS: 86400000  # 24 hours in milliseconds
      KAFKA_LOG_CLEANUP_POLICY: delete
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-init:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    entrypoint: >
      bash -c "
      echo 'Waiting for Kafka to be ready...'; 
      while ! nc -z kafka 9092; do sleep 1; done;
      echo 'Kafka is ready, creating topics...'; 
      kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic sms --if-not-exists && 
      kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic email --if-not-exists;
      echo 'Kafka topics created.'"
    healthcheck:
      test: ["CMD", "kafka-topics", "--describe", "--topic", "sms", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  sms-consumer:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./apps/consumers/Dockerfile
    environment:
      KAFKA_HOST: kafka:9092 
      KAFKA_CLIENT_ID: consumers
      CONSUMER_TYPE: sms
    restart: always  

  email-consumer:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./
      dockerfile: ./apps/consumers/Dockerfile
    environment:
      KAFKA_HOST: kafka:9092  
      KAFKA_CLIENT_ID: consumers
      CONSUMER_TYPE: email
    restart: always

  kafka-cleanup:
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
      while true; do
        echo 'Clearing Kafka data...';
        kafka-topics --bootstrap-server kafka:9092 --list | xargs -I {} kafka-topics --bootstrap-server kafka:9092 --delete --topic {};
        echo 'Kafka data cleared. Recreating topics...';
        kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic sms --if-not-exists;
        kafka-topics --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic email --if-not-exists;
        echo 'Kafka topics recreated. Sleeping for 24 hours...';
        sleep 86400;
      done"
    restart: always