global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'express_app'
    static_configs:
      - targets: ['http-server:3000'] 
    metrics_path: '/metrics'

  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']
    honor_labels: true