export {
  INVALID_CREDENTIALS,
  INVALID_GOOGLE_TOKEN,
  INVALID_INPUT,
  SERVER_ERROR,
  USER_ALREADY_EXISTS,
  OTP_SENT,
  USER_NOT_VERIFIED,
  INVALID_OTP,
  USER_NOT_REGISTERED,
  OTP_VERIFICATION_SUCCESSFUL,
  CANTEENS_NOT_FOUND,
  DISHES_NOT_FOUND,
  BROADCAST_QUANTITY,
  ORDER_HANDOVER,
  USER_NOT_AUTHORISED,
  REDIS_CONNECTION_ERROR
} from "./userConstants";
