# Main service for application traffic
apiVersion: v1
kind: Service
metadata:
  name: http-server
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: http-server-metrics
  labels:
    app: http-server
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 3000
    targetPort: 3000
  selector:
    app: http-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  labels: 
    app: http-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: http-server
        image: iamnithish/cuttheq_http:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP 
        - name: metrics
          containerPort: 3000
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: PORT
          value: "3000"
        - name: POD_NAMESPACE 
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - secretRef:
            name: app-secrets
        - configMapRef:
            name: app-config
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: prometheus_http_active_requests_
      target:
        type: AverageValue
        averageValue: "25"
  - type: Pods
    pods:
      metric:
        name: prometheus_http_request_spike_alert
      target:
        type: AverageValue
        averageValue: "1"