version: '3.8'

services:
  kafka:
    image: apache/kafka:3.7.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"  # Enable KRaft mode
      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT://localhost:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - kafka-network

  sms-consumer:
    build:
      context: .
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      KAFKA_CLIENT_ID: sms-consumer-client  # Add a specific client ID
      TYPE: sms
    networks:
      - kafka-network

  mail-consumer:
    build:
      context: .
    depends_on:
      - kafka
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      TYPE: 
    networks:
      - kafka-network

volumes:
  kafka-data:

networks:
  kafka-network:
    driver: bridge
